// Jawad TechX 
const { cmd } = require('../command');
const axios = require('axios');

cmd({
    pattern: "iqc",
    alias: ["sschat"],
    desc: "Generate fake iPhone quoted chat screenshot",
    category: "other",
    react: "🦇",
    filename: __filename
}, async (conn, mek, m, { from, reply, text }) => {
    try {
        if (!text) {
            return reply("❌ Please provide text\nExample: .iqc Hello World");
        }

        // Encode text for URL
        const encodedText = encodeURIComponent(text);

        // You can make time dynamic if you want, for now fixed (API requires it)
        const chatTime = "8:04";
        const statusBarTime = "11:20";

        const apiUrl = `https://api.deline.web.id/maker/iqc?text=${encodedText}&chatTime=${chatTime}&statusBarTime=${statusBarTime}`;

        // Send image with caption
        await conn.sendMessage(from, {
            image: { url: apiUrl },
            caption: "- *Generated By KHAN MD✅*"
        }, { quoted: mek });

    } catch (error) {
        console.error("IQC Error:", error);
        reply("❌ Failed to generate iPhone chat image");
    }
});
